import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { db } from './database.js';
import { buildRecommendations } from './aiService.js';
import { seedDemo } from './seed.js';

const app=express();
const allowedOrigins=(process.env.CLIENT_ORIGIN||'').split(',').map(origin=>origin.trim()).filter(Boolean);
app.use(cors({origin:allowedOrigins.length?(origin,callback)=>callback(null,!origin||allowedOrigins.includes(origin)):true}));app.use(express.json({limit:'1mb'}));
const secret=process.env.JWT_SECRET||(process.env.NODE_ENV==='production'?(()=>{throw new Error('JWT_SECRET must be set in production.')})():'local-development-secret-change-before-deploy');
const fail=(res,status,error)=>res.status(status).json({error});
const auth=(req,res,next)=>{try{const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!token)return fail(res,401,'Please sign in to continue.');req.user=jwt.verify(token,secret);next();}catch{return fail(res,401,'Your session has expired. Please sign in again.');}};
const scoped=(table,id,businessId)=>db.prepare(`SELECT id FROM ${table} WHERE id=? AND business_id=?`).get(id,businessId);
const scopedParty=(id,businessId,kind)=>db.prepare('SELECT id FROM parties WHERE id=? AND business_id=? AND kind=?').get(id,businessId,kind);
const safe=(fn)=>(req,res)=>Promise.resolve().then(()=>fn(req,res)).catch(e=>{console.error(e);if(!res.headersSent)fail(res,400,e.message||'The request could not be completed.');});

app.post('/api/auth/register',safe(async(req,res)=>{
  const {name,business_name,email,password}=req.body||{};if(!name?.trim()||!business_name?.trim()||!email||!password)return fail(res,400,'Name, business name, email, and password are required.');if(String(password).length<8)return fail(res,400,'Use a password with at least 8 characters.');
  const normalized=String(email).trim().toLowerCase();if(db.prepare('SELECT id FROM users WHERE email=?').get(normalized))return fail(res,409,'This email is already registered.');
  const create=db.transaction(()=>{const b=db.prepare("INSERT INTO businesses(name,email,trial_start,trial_end) VALUES(?,?,datetime('now'),datetime('now','+60 days'))").run(business_name.trim(),normalized);const id=Number(b.lastInsertRowid);db.prepare('INSERT INTO settings(business_id) VALUES(?)').run(id);const role=db.prepare('INSERT INTO roles(business_id,name,permissions) VALUES(?,?,?)').run(id,'Owner','["*"]');const u=db.prepare('INSERT INTO users(business_id,name,email,password_hash,role) VALUES(?,?,?,?,?)').run(id,name.trim(),normalized,bcrypt.hashSync(password,10),'Owner');db.prepare('INSERT INTO employees(business_id,user_id,role_id) VALUES(?,?,?)').run(id,u.lastInsertRowid,role.lastInsertRowid);return {id:Number(u.lastInsertRowid),business_id:id,name:name.trim(),email:normalized,role:'Owner'};});const user=create();res.status(201).json({token:jwt.sign(user,secret,{expiresIn:'7d'}),user});
}));
app.post('/api/auth/login',safe(async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();const user=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!user||!await bcrypt.compare(String(req.body?.password||''),user.password_hash))return fail(res,401,'Email or password is incorrect.');const payload={id:user.id,business_id:user.business_id,name:user.name,email:user.email,role:user.role};res.json({token:jwt.sign(payload,secret,{expiresIn:'7d'}),user:payload});}));
app.get('/api/auth/me',auth,safe((req,res)=>{const user=db.prepare('SELECT id,business_id,name,email,role FROM users WHERE id=?').get(req.user.id);const business=db.prepare('SELECT id,name,address,phone,gst_number,currency,trial_start,trial_end,subscription_plan,subscription_status FROM businesses WHERE id=?').get(req.user.business_id);if(!user||!business)return fail(res,401,'Account could not be found.');res.json({user,business});}));

app.get('/api/dashboard',auth,safe((req,res)=>{const b=req.user.business_id;const stats=db.prepare(`SELECT (SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND date(created_at)=date('now')) today_sales,(SELECT COUNT(*) FROM sales WHERE business_id=? AND date(created_at)=date('now')) today_orders,(SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND created_at>=datetime('now','-30 days')) revenue_month,(SELECT COUNT(*) FROM products WHERE business_id=? AND archived=0) products,(SELECT COALESCE(SUM(stock*cost),0) FROM products WHERE business_id=? AND archived=0) inventory_value,(SELECT COUNT(*) FROM products WHERE business_id=? AND stock<=min_stock AND stock>0 AND archived=0) low_stock,(SELECT COUNT(*) FROM products WHERE business_id=? AND stock=0 AND archived=0) out_of_stock,(SELECT COUNT(*) FROM purchases WHERE business_id=? AND payment_status='Pending') pending_purchases`).get(...Array(8).fill(b));const sales=db.prepare("SELECT date(created_at) day,ROUND(SUM(total),2) total FROM sales WHERE business_id=? AND created_at>=datetime('now','-6 days') GROUP BY date(created_at) ORDER BY day").all(b);const recent=db.prepare('SELECT s.id,s.total,s.payment_method,s.status,s.created_at,p.name customer FROM sales s LEFT JOIN parties p ON p.id=s.party_id AND p.business_id=s.business_id WHERE s.business_id=? ORDER BY s.id DESC LIMIT 6').all(b);const top=db.prepare('SELECT p.name,SUM(i.quantity) units FROM sale_items i JOIN sales s ON s.id=i.sale_id JOIN products p ON p.id=i.product_id WHERE s.business_id=? AND p.business_id=? GROUP BY p.id ORDER BY units DESC LIMIT 5').all(b,b);res.json({stats,sales,recent,top,recommendations:buildRecommendations(db,b)});}));

app.get('/api/products',auth,safe((req,res)=>res.json(db.prepare('SELECT p.*,s.name supplier_name FROM products p LEFT JOIN parties s ON s.id=p.supplier_id AND s.business_id=p.business_id WHERE p.business_id=? AND p.archived=0 ORDER BY p.name').all(req.user.business_id))));
app.post('/api/products',auth,safe((req,res)=>{const d=req.body||{};if(!d.name?.trim()||!d.sku?.trim())return fail(res,400,'Product name and SKU are required.');if(d.supplier_id&&!scopedParty(d.supplier_id,req.user.business_id,'supplier'))return fail(res,400,'Supplier not found.');const r=db.prepare('INSERT INTO products(business_id,name,sku,barcode,category,brand,cost,price,stock,min_stock,max_stock,gst,expiry_date,batch_number,supplier_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(req.user.business_id,d.name.trim(),d.sku.trim(),d.barcode||'',d.category||'General',d.brand||'',+d.cost||0,+d.price||0,Math.max(0,+d.stock||0),Math.max(0,+d.min_stock||0),+d.max_stock||0,+d.gst||0,d.expiry_date||'',d.batch_number||'',d.supplier_id||null);if(+d.stock)db.prepare("INSERT INTO inventory_movements(business_id,product_id,change,reason) VALUES(?,?,?,'Opening stock')").run(req.user.business_id,r.lastInsertRowid,+d.stock);res.status(201).json(db.prepare('SELECT * FROM products WHERE id=?').get(r.lastInsertRowid));}));
app.put('/api/products/:id',auth,safe((req,res)=>{const b=req.user.business_id,id=+req.params.id;if(!scoped('products',id,b))return fail(res,404,'Product not found.');const d=req.body||{};const fields=['name','sku','barcode','category','brand','cost','price','min_stock','max_stock','gst','expiry_date','batch_number','supplier_id'];const setters=fields.filter(k=>d[k]!==undefined);if(!setters.length)return res.json(db.prepare('SELECT * FROM products WHERE id=?').get(id));if(d.supplier_id&&!scopedParty(d.supplier_id,b,'supplier'))return fail(res,400,'Supplier not found.');const sql=setters.map(k=>`${k}=?`).join(',');db.prepare(`UPDATE products SET ${sql} WHERE id=? AND business_id=?`).run(...setters.map(k=>k==='supplier_id'&&d[k]===''?null:d[k]),id,b);res.json(db.prepare('SELECT * FROM products WHERE id=?').get(id));}));
app.delete('/api/products/:id',auth,safe((req,res)=>{const id=+req.params.id,b=req.user.business_id;if(!scoped('products',id,b))return fail(res,404,'Product not found.');db.prepare('UPDATE products SET archived=1 WHERE id=? AND business_id=?').run(id,b);res.json({ok:true});}));
app.post('/api/inventory/adjust',auth,safe((req,res)=>{const {product_id,change,reason='Manual adjustment'}=req.body||{};const b=req.user.business_id,p=db.prepare('SELECT * FROM products WHERE id=? AND business_id=? AND archived=0').get(+product_id,b);const amount=Number(change);if(!p||!Number.isInteger(amount)||amount===0)return fail(res,400,'Choose a product and a non-zero whole-number adjustment.');if(p.stock+amount<0)return fail(res,400,'Adjustment cannot make stock negative.');const update=db.transaction(()=>{db.prepare('UPDATE products SET stock=stock+? WHERE id=?').run(amount,p.id);db.prepare('INSERT INTO inventory_movements(business_id,product_id,change,reason) VALUES(?,?,?,?)').run(b,p.id,amount,String(reason).slice(0,120));});update();res.json({ok:true});}));
app.get('/api/inventory/movements',auth,safe((req,res)=>res.json(db.prepare('SELECT m.*,p.name product_name,p.sku FROM inventory_movements m JOIN products p ON p.id=m.product_id WHERE m.business_id=? ORDER BY m.id DESC LIMIT 100').all(req.user.business_id))));

app.get('/api/parties',auth,safe((req,res)=>{const kind=req.query.kind;const sql='SELECT * FROM parties WHERE business_id=?'+(['customer','supplier'].includes(kind)?' AND kind=?':'')+' ORDER BY name';res.json(['customer','supplier'].includes(kind)?db.prepare(sql).all(req.user.business_id,kind):db.prepare(sql).all(req.user.business_id));}));
app.post('/api/parties',auth,safe((req,res)=>{const d=req.body||{};if(!d.name?.trim()||!['customer','supplier'].includes(d.kind))return fail(res,400,'Name and a valid party type are required.');const r=db.prepare('INSERT INTO parties(business_id,name,kind,company,email,phone,address,gst_number,payment_terms) VALUES(?,?,?,?,?,?,?,?,?)').run(req.user.business_id,d.name.trim(),d.kind,d.company||'',d.email||'',d.phone||'',d.address||'',d.gst_number||'',d.payment_terms||'');res.status(201).json(db.prepare('SELECT * FROM parties WHERE id=?').get(r.lastInsertRowid));}));
app.put('/api/parties/:id',auth,safe((req,res)=>{const b=req.user.business_id,id=+req.params.id;if(!scoped('parties',id,b))return fail(res,404,'Record not found.');const fields=['name','company','email','phone','address','gst_number','payment_terms'];const keys=fields.filter(k=>req.body?.[k]!==undefined);if(keys.length)db.prepare(`UPDATE parties SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=? AND business_id=?`).run(...keys.map(k=>req.body[k]),id,b);res.json(db.prepare('SELECT * FROM parties WHERE id=?').get(id));}));

app.get('/api/sales',auth,safe((req,res)=>res.json(db.prepare('SELECT s.*,p.name customer FROM sales s LEFT JOIN parties p ON p.id=s.party_id AND p.business_id=s.business_id WHERE s.business_id=? ORDER BY s.id DESC LIMIT 250').all(req.user.business_id))));
app.get('/api/sales/:id',auth,safe((req,res)=>{const s=db.prepare('SELECT s.*,p.name customer,p.phone FROM sales s LEFT JOIN parties p ON p.id=s.party_id AND p.business_id=s.business_id WHERE s.id=? AND s.business_id=?').get(+req.params.id,req.user.business_id);if(!s)return fail(res,404,'Sale not found.');s.items=db.prepare('SELECT i.*,p.name,p.sku FROM sale_items i JOIN products p ON p.id=i.product_id WHERE i.sale_id=? AND p.business_id=?').all(s.id,req.user.business_id);res.json(s);}));
app.post('/api/sales',auth,safe((req,res)=>{const {items,party_id=null,payment_method='Cash',discount=0}=req.body||{};const b=req.user.business_id;if(!Array.isArray(items)||!items.length)return fail(res,400,'Add at least one item.');if(party_id&&!scopedParty(party_id,b,'customer'))return fail(res,400,'Customer not found.');if(!['Cash','UPI','Card','Other'].includes(payment_method))return fail(res,400,'Select a valid payment method.');const create=db.transaction(()=>{let subtotal=0;const lines=items.map(i=>{const p=db.prepare('SELECT * FROM products WHERE id=? AND business_id=? AND archived=0').get(+i.product_id,b),q=Number(i.quantity);if(!p||!Number.isInteger(q)||q<1)throw Error('An item or quantity is invalid.');if(p.stock<q)throw Error(`${p.name} has only ${p.stock} in stock.`);subtotal+=p.price*q;return{p,q};});const discountValue=Math.max(0,Math.min(subtotal,+discount||0));const grossTax=lines.reduce((sum,{p,q})=>sum+(p.price*q*(+p.gst||0)/100),0);const tax=subtotal?grossTax*(subtotal-discountValue)/subtotal:0;const total=Math.max(0,subtotal-discountValue+tax);const s=db.prepare('INSERT INTO sales(business_id,party_id,total,subtotal,discount,tax,payment_method) VALUES(?,?,?,?,?,?,?)').run(b,party_id,total,subtotal,discountValue,tax,payment_method);db.prepare('INSERT INTO payments(business_id,sale_id,amount,method,status) VALUES(?,?,?,?,?)').run(b,s.lastInsertRowid,total,payment_method,'Completed');for(const{p,q}of lines){db.prepare('INSERT INTO sale_items(sale_id,product_id,quantity,unit_price) VALUES(?,?,?,?)').run(s.lastInsertRowid,p.id,q,p.price);db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(q,p.id);db.prepare("INSERT INTO inventory_movements(business_id,product_id,change,reason,reference_id) VALUES(?,?,?,'Sale',?)").run(b,p.id,-q,s.lastInsertRowid);}return{id:Number(s.lastInsertRowid),subtotal,discount:discountValue,tax,total};});res.status(201).json(create());}));
app.get('/api/purchases',auth,safe((req,res)=>res.json(db.prepare('SELECT x.*,p.name supplier FROM purchases x LEFT JOIN parties p ON p.id=x.supplier_id AND p.business_id=x.business_id WHERE x.business_id=? ORDER BY x.id DESC LIMIT 200').all(req.user.business_id))));
app.post('/api/purchases',auth,safe((req,res)=>{const {supplier_id=null,items,invoice_number='',payment_status='Paid'}=req.body||{};const b=req.user.business_id;if(!Array.isArray(items)||!items.length)return fail(res,400,'Add at least one item.');if(supplier_id&&!scopedParty(supplier_id,b,'supplier'))return fail(res,400,'Supplier not found.');const create=db.transaction(()=>{let total=0;const lines=items.map(i=>{const p=db.prepare('SELECT * FROM products WHERE id=? AND business_id=? AND archived=0').get(+i.product_id,b);const q=Number(i.quantity),cost=Number(i.unit_cost??p?.cost);if(!p||!Number.isInteger(q)||q<1||!Number.isFinite(cost)||cost<0)throw Error('A product, quantity, or cost is invalid.');total+=q*cost;return{p,q,cost};});const r=db.prepare('INSERT INTO purchases(business_id,supplier_id,total,invoice_number,payment_status) VALUES(?,?,?,?,?)').run(b,supplier_id,total,invoice_number,['Paid','Pending'].includes(payment_status)?payment_status:'Paid');for(const{p,q,cost}of lines){db.prepare('INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_cost) VALUES(?,?,?,?)').run(r.lastInsertRowid,p.id,q,cost);db.prepare('UPDATE products SET stock=stock+?,cost=? WHERE id=?').run(q,cost,p.id);db.prepare("INSERT INTO inventory_movements(business_id,product_id,change,reason,reference_id) VALUES(?,?,?,'Purchase',?)").run(b,p.id,q,r.lastInsertRowid);}return{id:Number(r.lastInsertRowid),total};});res.status(201).json(create());}));
app.get('/api/ai/insights',auth,safe((req,res)=>res.json(buildRecommendations(db,req.user.business_id))));
app.put('/api/business',auth,safe((req,res)=>{const fields=['name','address','phone','gst_number','currency'];const keys=fields.filter(k=>req.body?.[k]!==undefined);if(keys.length)db.prepare(`UPDATE businesses SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`).run(...keys.map(k=>req.body[k]),req.user.business_id);res.json({ok:true});}));
app.get('/api/employees',auth,safe((req,res)=>res.json(db.prepare('SELECT id,name,email,role,created_at FROM users WHERE business_id=? ORDER BY id').all(req.user.business_id))));
app.get('/api/health',(_req,res)=>res.json({ok:true}));

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
app.use(express.static(path.join(root,'dist')));
app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api/')&&req.accepts('html'))return res.sendFile(path.join(root,'dist','index.html'),err=>err&&next());next();});
if(process.env.SEED_DEMO==='true')await seedDemo();
const port=process.env.PORT||3001;app.listen(port,()=>console.log(`StockPilot listening at http://localhost:${port}`));
