CREATE TABLE IF NOT EXISTS businesses (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, address TEXT DEFAULT '', phone TEXT DEFAULT '', gst_number TEXT DEFAULT '', currency TEXT NOT NULL DEFAULT 'INR',
 trial_start TEXT DEFAULT CURRENT_TIMESTAMP, trial_end TEXT, subscription_plan TEXT NOT NULL DEFAULT 'Starter', subscription_status TEXT NOT NULL DEFAULT 'trial', created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'Owner', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, name TEXT NOT NULL, permissions TEXT NOT NULL DEFAULT '[]', UNIQUE(business_id,name), FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS employees (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, user_id INTEGER, phone TEXT DEFAULT '', role_id INTEGER, status TEXT NOT NULL DEFAULT 'Active', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, name TEXT NOT NULL, UNIQUE(business_id,name), FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS parties (
 id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, name TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('customer','supplier')), company TEXT DEFAULT '', email TEXT DEFAULT '', phone TEXT DEFAULT '', address TEXT DEFAULT '', gst_number TEXT DEFAULT '', payment_terms TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id)
);
CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, name TEXT NOT NULL, sku TEXT NOT NULL, barcode TEXT DEFAULT '', category TEXT NOT NULL DEFAULT 'General', brand TEXT DEFAULT '', cost REAL NOT NULL DEFAULT 0, price REAL NOT NULL DEFAULT 0, stock INTEGER NOT NULL DEFAULT 0,
 min_stock INTEGER NOT NULL DEFAULT 5, max_stock INTEGER DEFAULT 0, gst REAL DEFAULT 0, expiry_date TEXT DEFAULT '', batch_number TEXT DEFAULT '', supplier_id INTEGER, archived INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(business_id,sku), FOREIGN KEY(business_id) REFERENCES businesses(id), FOREIGN KEY(supplier_id) REFERENCES parties(id)
);
CREATE TABLE IF NOT EXISTS sales (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, party_id INTEGER, total REAL NOT NULL, subtotal REAL NOT NULL DEFAULT 0, discount REAL NOT NULL DEFAULT 0, tax REAL NOT NULL DEFAULT 0, payment_method TEXT NOT NULL DEFAULT 'Cash', status TEXT NOT NULL DEFAULT 'Completed', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id), FOREIGN KEY(party_id) REFERENCES parties(id));
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, sale_id INTEGER NOT NULL, amount REAL NOT NULL, method TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Completed', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id), FOREIGN KEY(sale_id) REFERENCES sales(id));
CREATE TABLE IF NOT EXISTS sale_items (id INTEGER PRIMARY KEY, sale_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, unit_price REAL NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS purchases (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, supplier_id INTEGER, total REAL NOT NULL, invoice_number TEXT DEFAULT '', payment_status TEXT DEFAULT 'Paid', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id), FOREIGN KEY(supplier_id) REFERENCES parties(id));
CREATE TABLE IF NOT EXISTS purchase_items (id INTEGER PRIMARY KEY, purchase_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, unit_cost REAL NOT NULL, FOREIGN KEY(purchase_id) REFERENCES purchases(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS inventory_movements (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, product_id INTEGER NOT NULL, change INTEGER NOT NULL, reason TEXT NOT NULL, reference_id INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS ai_recommendations (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, kind TEXT NOT NULL, priority TEXT NOT NULL, title TEXT NOT NULL, detail TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Open', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS settings (business_id INTEGER PRIMARY KEY, currency TEXT NOT NULL DEFAULT 'INR', default_tax REAL NOT NULL DEFAULT 0, low_stock_threshold INTEGER NOT NULL DEFAULT 5, theme TEXT NOT NULL DEFAULT 'light', FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE VIEW IF NOT EXISTS suppliers AS SELECT * FROM parties WHERE kind='supplier';
CREATE VIEW IF NOT EXISTS customers AS SELECT * FROM parties WHERE kind='customer';
